language: ruby

rvm:
- 2.3

install: gem install jekyll jekyll-paginate jemoji html-proofer
script: ./scripts/generate-categories && ./scripts/generate-tags && jekyll serve --baseurl "" --detach && htmlproofer ./_site --disable-external --empty-alt-ignore

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true JEKYLL_ENV=production
    
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  repo: kastoestoramadus/kastoestoramadus.github.io
  target-branch: master
  fqdn: blog.ww86.eu
  on:
    branch: master
